blank_issues_enabled: false
contact_links:
  - name: Documentación del Proyecto
    url: "https://github.com/brayandiazc/dev-setup-ubuntu-es#readme"
    about: Consulta el README y la carpeta docs/ del proyecto
  - name: Discusiones de la Comunidad
    url: "https://github.com/brayandiazc/dev-setup-ubuntu-es/discussions"
    about: Únete a las discusiones para hacer preguntas generales
